title: Super Laser Cat
author: Ian Blackledge
author_url: https://github.com/IanBlackledge
description: ""

include:
  - _pages

sass:
  style: expanded

defaults:
  - scope:
      path: "_pages"
      type: "pages"
    values:
      permalink: :basename
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: grid
      permalink: :categories/:short_year-:i_month-:i_day-:title
