title: Super Laser Cat
author: Ian Blackledge
author_url: https://github.com/IanBlackledge
description: ""

include:
  - _pages

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
